# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.cache/wt [current_project]
set_property parent.project_path D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/imports/new/CLAdder.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/ShiftLeft.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/RoundBlock.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/ShiftRight.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/Comparator.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/Adder.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/StandardizingBlock.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/OpEnable.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/NumberProcessingUnit.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/ROM.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/FPAdder.vhd
  D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/sources_1/new/FPU.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files D:/Faculta/IIIsem1/SCS/Lab/FPU/FPU.srcs/constrs_1/new/basys3.xdc]


synth_design -top FPU -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef FPU.dcp

catch { report_utilization -file FPU_utilization_synth.rpt -pb FPU_utilization_synth.pb }
